const id = (pgm) => ({ type: 'uuid', primaryKey: true, default: pgm.func('gen_random_uuid()') });
exports.up = (pgm) => {
  pgm.createTable('document_links', { id: id(pgm), from_document_id: { type: 'uuid', notNull: true, references: 'documents', onDelete: 'cascade' }, from_step_key: 'text', to_document_id: { type: 'uuid', references: 'documents', onDelete: 'cascade' }, to_block_id: { type: 'uuid', references: 'blocks', onDelete: 'cascade' }, to_field_name: { type: 'text', references: 'crm_fields', onDelete: 'cascade' }, to_source_id: { type: 'uuid', references: 'sources', onDelete: 'cascade' }, type: { type: 'text', notNull: true }, origin: { type: 'text', notNull: true, default: 'detected' } });
  pgm.createIndex('document_links', 'to_document_id'); pgm.createIndex('document_links', 'from_document_id');
  pgm.createTable('notes', { id: id(pgm), document_id: { type: 'uuid', notNull: true, references: 'documents', onDelete: 'cascade' }, step_key: 'text', author_id: { type: 'uuid', notNull: true, references: 'users' }, text: { type: 'text', notNull: true }, created_at: { type: 'timestamptz', notNull: true, default: pgm.func('now()') }, deleted_at: 'timestamptz' });
  pgm.createTable('note_likes', { note_id: { type: 'uuid', notNull: true, references: 'notes', onDelete: 'cascade' }, user_id: { type: 'uuid', notNull: true, references: 'users', onDelete: 'cascade' } }, { constraints: { primaryKey: ['note_id', 'user_id'] } });
  pgm.createTable('pins', { user_id: { type: 'uuid', notNull: true, references: 'users', onDelete: 'cascade' }, document_id: { type: 'uuid', notNull: true, references: 'documents', onDelete: 'cascade' }, created_at: { type: 'timestamptz', notNull: true, default: pgm.func('now()') } }, { constraints: { primaryKey: ['user_id', 'document_id'] } });
  pgm.createTable('recent_views', { user_id: { type: 'uuid', notNull: true, references: 'users', onDelete: 'cascade' }, document_id: { type: 'uuid', notNull: true, references: 'documents', onDelete: 'cascade' }, viewed_at: { type: 'timestamptz', notNull: true, default: pgm.func('now()') }, count: { type: 'integer', notNull: true, default: 1 } }, { constraints: { primaryKey: ['user_id', 'document_id'] } });
  pgm.createTable('drafts', { id: id(pgm), user_id: { type: 'uuid', notNull: true, references: 'users', onDelete: 'cascade' }, document_id: { type: 'uuid', references: 'documents', onDelete: 'cascade' }, draft_key: { type: 'text', notNull: true }, payload: { type: 'jsonb', notNull: true }, updated_at: { type: 'timestamptz', notNull: true, default: pgm.func('now()') } });
  pgm.addConstraint('drafts', 'drafts_user_key_unique', { unique: ['user_id', 'draft_key'] });
  pgm.createTable('user_preferences', { user_id: { type: 'uuid', primaryKey: true, references: 'users', onDelete: 'cascade' }, prefs: { type: 'jsonb', notNull: true, default: '{}' } });
};
exports.down = (pgm) => { for (const t of ['user_preferences','drafts','recent_views','pins','note_likes','notes','document_links']) pgm.dropTable(t); };
