/** One factory for every TanStack Query key, so SSE invalidation and hooks can never drift. */
export const keys = {
  me: ['me'] as const,
  health: ['health'] as const,
  prefs: ['prefs'] as const,
  providers: ['providers'] as const,
  docs: (q: unknown = '*') => ['documents', q] as const,
  doc: (id: string) => ['document', id] as const,
  related: (id: string) => ['related', id] as const,
  links: (id: string) => ['links', id] as const,
  notes: (id: string) => ['notes', id] as const,
  versions: (id: string) => ['versions', id] as const,
  version: (id: string, v: number) => ['version', id, v] as const,
  diff: (id: string, from: number, to: number) => ['diff', id, from, to] as const,
  draft: (id: string) => ['draft', id] as const,
  blocks: ['blocks'] as const,
  blockUsage: (id: string) => ['blockUsage', id] as const,
  fields: ['fields'] as const,
  fieldUsage: (n: string) => ['fieldUsage', n] as const,
  scripts: ['scripts'] as const,
  search: (q: string, types?: string) => ['search', q, types ?? ''] as const,
  trash: ['trash'] as const,
  sources: ['sources'] as const,
  revision: (id: string, rev: string) => ['revision', id, rev] as const,
  suggestions: (q: unknown = '*') => ['suggestions', q] as const,
  admin: {
    users: (q: unknown = '*') => ['admin', 'users', q] as const,
    roles: ['admin', 'roles'] as const,
    groups: ['admin', 'groups'] as const,
    sessions: ['admin', 'sessions'] as const,
    audit: (q: unknown = '*') => ['admin', 'audit', q] as const,
  },
};
